<?php

namespace App\Http\Controllers;

use App\Models\investor;
use App\Models\petani;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;

class BantutaniController extends Controller
{
    public function index()
    {
        return $this->render("bantutani.index"); // TODO: Change the autogenerated stub
    }

    public function daftartaniform()
    {
        return $this->render("bantutani.daftartani");
    }

    public function daftartani(Request $request)
    {
        $data = $request->validate([
            'name' => 'required',
            'phone' => 'required',
            'farmerdesc' => 'required',
            'landdesc' => 'required',
            'fund' => 'required'
        ]);
        $data["user_id"] = Session::get("auth")->id;
        $petani = new petani($data);
        $petani->save();
        return redirect()->intended();
    }

    public function investorform()
    {
        $petanis = petani::all();
        return $this->render("bantutani.investor", ["petanis" => $petanis]);
    }

    public function investorconfirm(Request $request)
    {
        $data = $request->validate([
            'name' => 'required',
            'phone' => 'required',
            'petani_id' => 'required',
            'fund' => 'required'
        ]);
        $data["user_id"] = Session::get("auth")->id;
        Session::put("payload", $data);
        return $this->render("bantutani.confirmation");
    }

    public function investor()
    {
        $investor = new investor(Session::get("payload"));
        $investor->save();
        return redirect("https://wa.me/6281234567890");
    }
}
